### ISSUE TITLE
Paper-input in paper-collapse-item does not work properly

### ISSUE THREAD

**Issue by steveHernandez12** [Collaborne/paper-collapse-item#19] opened 2017-06-22 02:08 UTC
If you add a paper-input into a paper-collapse-item the input is not able to register the spacebar.

**Comment by ronnyroeller** [comment] 2017-06-22 07:38
Thanks for the report. Could you please provide a reproduction case (e.g. based on https://jsbin.com/cagaye/edit?html,output)?

**Comment by schlm3** [comment] 2017-10-12 13:29
Having the same issue. It is caused by https://github.com/PolymerElements/paper-item/issues/103 and is closely related to https://github.com/PolymerElements/paper-item/issues/28

**Comment by schlm3** [comment] 2017-10-12 13:49
Demo code:
```
<paper-collapse-item header="Spacebar Problem Demo" opened>
    <paper-input label="Enter Text with spaces"/>
</paper-collapse-item>
```

**Comment by schlm3** [comment] 2017-10-13 09:58
I am using paper-collapse-item with polymer 1.0.x, however, I just verified that the problem still exists in the most recent 2.x polymer version.

**Comment by ankon** [comment] 2017-10-20 15:13
https://jsbin.com/fomefemuxa/edit?html,output indeed reproduces the issue (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3236.7 Safari/537.36)

**Comment by LudovicDubois** [comment] 2017-10-20 18:55
I have the same problem!

**Comment by ronnyroeller** [comment] 2017-10-24 07:54
Thanks to everybody for providing all the input! A special thanks to @schlm3 for pointing to the root cause in the underlying `<paper-item>` element. You can follow the issue here: https://github.com/PolymerElements/paper-item/issues/103.

Based on the proposed [workaround](https://github.com/PolymerElements/paper-item/issues/103#issuecomment-336411983) by @SPessall:
```
<paper-collapse-item id="collapseItem" header="Item with paper-input" opened>
  <paper-input label="Enter Text with spaces"></paper-input>
</paper-collapse-item>

<script>
  window.addEventListener('WebComponentsReady', function(e) {
    const bindScope = document.querySelector('#input');
    const item = bindScope.$.collapseItem.shadowRoot.querySelector('paper-item');
    item._spaceKeyDownHandler = () => {};
  });
</script>
```

**Comment by hyyan** [comment] 2017-11-21 10:25
@ronnyroeller any update on this one?

**Comment by ronnyroeller** [comment] 2017-11-21 10:29
@hyyan See my last [comment](https://github.com/Collaborne/paper-collapse-item/issues/19#issuecomment-338905929). This is basically an upstream issue that needs to be fixed in paper-item (the comment contains the workaround).

**Comment by hyyan** [comment] 2017-11-21 10:37
@ronnyroeller I have read your last comment, I think this a lot of work if you have more than one input in paper-collapse-item.

Why use paper-item ?! we can create a special one for this component .

Example : 

```html 
<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../iron-flex-layout/iron-flex-layout.html">
<link rel="import" href="../paper-item/paper-item-behavior.html">
<link rel="import" href="../paper-item/paper-item-shared-styles.html">

<dom-module id="paper-item-fixed">
  <template>
    <style include="paper-item-shared-styles"></style>
    <style>
      :host {
        @apply(--layout-horizontal);
        @apply(--layout-center);
        @apply(--paper-font-subhead);
        @apply(--paper-item);
      }
    </style>

    <slot></slot>
  </template>

  <script>
    Polymer({
      is: 'paper-item-fixed',
      behaviors: [
        Polymer.IronControlState,
        Polymer.PaperItemBehaviorImpl
      ]
    });
  </script>
</dom-module>

```

what do you think ?

**Comment by ronnyroeller** [comment] 2017-11-21 15:20
> Why use paper-item ?! we can create a special one for this component .

The only reason was to create visual consistency with Material Design spec/standard Polymer elements.

I won't be able to look into this any time soon but if somebody provides a PR - happy to merge.

**Comment by hyyan** [comment] 2017-11-21 15:25
I will send another PR to close this issue later this week when I have some time

**Comment by PatrykSzwer** [comment] 2017-12-04 09:02
Any progress about this issue?

**Comment by hyyan** [comment] 2017-12-04 09:05
@PatrykSzwer I will send a PR this evening to solve the issue, I was just too busy lately

**Comment by hyyan** [comment] 2017-12-04 18:40
@PatrykSzwer I have sent a PR. waiting for @ronnyroeller review

**Comment by hyyan** [comment] 2017-12-08 07:01
@ronnyroeller is this still an issue?

**Comment by ronnyroeller** [comment] 2017-12-08 08:00
Resolved indeed

**Closed as completed by ronnyroeller** 2017-12-08 08:00 UTC
